// Generated by https://quicktype.io

export interface IListWaterControlDTO {
    data:       Data;
    message:    null;
    succeed:    boolean;
    errors:     null;
    statusCode: number;
}

export interface Data {
    totalHours:                   number;
    amountWaterCaptured:          number;
    amountWaterSupplied:          number;
    aluminumSulfate:              number;
    sodiumHypochlorite:           number;
    chlorineGas:                  number;
    particlesPerMillion:          number;
    nationalIdentificationNumber: string;
    idPlant:                      number;
}
