// Generated by https://quicktype.io

export interface IWaterControlForm {
    totalHours:                   number;
    amountWaterCaptured:          number;
    amountWaterSupplied:          number;
    aluminumSulfate:              number;
    sodiumHypochlorite:           number;
    chlorineGas:                  number;
    particlesPerMillion:          number;
    nationalIdentificationNumber: string;
    idPlant:                      number;
}
 